apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-portfolio-cluster
  region: ap-south-1

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
      - namespace: game-2048
